### ISSUE TITLE
'mc admin user' command not working

### ISSUE THREAD

**Issue by honnorat** [jessestuart/minio-multiarch#8]
Hi,

I do not manage to create / list users using 'mc admin user' command and my docker minio-multiarch installation. 

I have setup the minio store using docker-compose:
```yaml
# docker-compose.yml
version: '3.7'
services:
  store:
    container_name: store
    image: jessestuart/minio:RELEASE.2019-10-12T01-39-57Z-arm64
    volumes:
      - type: bind
        source: ./minio-data
        target: /data
    ports:
      - 9000:9000
    env_file:
      - minio.env
    command: server /data
```
Accessing the store using `mc ls` or via the web interface works as expected.

However, when I want to use 'admin user' mc subcommand, I get the following error message:
```bash
$ mc admin user list store
mc: <ERROR> Cannot list user: sio: unsupported version.
$ mc admin user list --json store
{
 "status": "error",
 "error": {
  "message": "Cannot list user",
  "cause": {
   "message": "sio: unsupported version",
   "error": {}
  },
  "type": "fatal",
  "sysinfo": {
   "host.arch": "arm64",
   "host.cpus": "4",
   "host.lang": "go1.13.1",
   "host.name": "8206820f6f3d",
   "host.os": "linux",
   "mem.heap.total": "134 MB",
   "mem.heap.used": "68 MB",
   "mem.total": "142 MB",
   "mem.used": "68 MB"
  }
 }
}
```
What's wrong ? No problem with minio/minio image.
